#!/usr/bin/env node
// Generates static-host configs from app/security.mjs so security headers are
// identical on every platform. `--check` fails (CI) if committed files drift.
//   node app/scripts/gen-deploy.mjs            # rewrite app/vercel.json + app/deploy/nginx.conf
//   node app/scripts/gen-deploy.mjs --check    # verify
//   node app/scripts/gen-deploy.mjs --nginx-out /etc/nginx/conf.d/default.conf   (Docker, uses VITE_* env)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { securityHeaders } from "../security.mjs";

const root = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const env = Object.fromEntries(Object.entries(process.env).filter(([k]) => k.startsWith("VITE_")));

export function vercelJson(e = {}) {
  const headers = Object.entries(securityHeaders(e)).map(([key, value]) => ({ key, value }));
  return JSON.stringify({
    $schema: "https://openapi.vercel.sh/vercel.json",
    buildCommand: "npm run build",
    outputDirectory: "dist",
    headers: [
      { source: "/(.*)", headers },
      { source: "/assets/(.*)", headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }] },
      { source: "/index.html", headers: [{ key: "Cache-Control", value: "no-cache" }] },
    ],
  }, null, 2) + "\n";
}

export function nginxConf(e = {}) {
  const add = Object.entries(securityHeaders(e)).map(([k, v]) => `    add_header ${k} "${v}" always;`).join("\n");
  return `# Generated by app/scripts/gen-deploy.mjs from app/security.mjs — do not edit by hand.
server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    charset utf-8;

    gzip on;
    gzip_vary on;
    gzip_types text/css application/javascript application/json image/svg+xml application/manifest+json;
    gzip_min_length 1024;

    # Static site: no meaningful POST bodies — reject big ones (DoS budget).
    client_max_body_size 2k;

${add}

    location /assets/ {
        access_log off;
${add.replace(/^ {4}/gm, "        ")}
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }

    location = /index.html {
${add.replace(/^ {4}/gm, "        ")}
        add_header Cache-Control "no-cache" always;
    }

    location = /healthz { access_log off; add_header Content-Type text/plain; return 200 "ok"; }

    # hash router: every unknown path serves the app shell
    location / { try_files $uri $uri/ /index.html; }

    # never serve dotfiles / source maps — except .well-known/ (security.txt,
    # checklist 7.2): the dotfile regex below is a PCRE with a negative lookahead
    location ~ /\\.(?!well-known/) { deny all; }
    location ~ \\.map$ { deny all; }
}
`;
}

const args = process.argv.slice(2);
const outIdx = args.indexOf("--nginx-out");
if (outIdx >= 0) {
  writeFileSync(args[outIdx + 1], nginxConf(env));
  console.log(`nginx config → ${args[outIdx + 1]}`);
} else {
  const files = { "vercel.json": vercelJson(), "deploy/nginx.conf": nginxConf() };
  let bad = 0;
  for (const [p, body] of Object.entries(files)) {
    if (args.includes("--check")) {
      let cur = ""; try { cur = readFileSync(root(p), "utf8"); } catch { /* missing */ }
      if (cur !== body) { console.error(`✗ app/${p} is out of date — run: node app/scripts/gen-deploy.mjs`); bad++; } else console.log(`✓ app/${p}`);
    } else { writeFileSync(root(p), body); console.log(`wrote app/${p}`); }
  }
  process.exit(bad ? 1 : 0);
}
